name: Tests

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2, 8.3]
        laravel: [11]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-p${{ matrix.php }}-l${{ matrix.laravel }}-${{ hashFiles('composer.json') }}
          restore-keys: composer-p${{ matrix.php }}-l${{ matrix.laravel }}-

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, sqlite, pdo_sqlite
          tools: composer:v2
          coverage: none
          ini-values: error_reporting=E_ALL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist

      - name: Execute tests
        env:
          APP_ENV: testing
          DB_CONNECTION: testing
          DB_DATABASE: ":memory:"
        run: composer test

      # - name: Execute tests with hashids turned on
      #   run: composer test-hashids
