name: Tests

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2, 8.3]
        laravel: [11]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Laravel environment
        run: |
          cp .env.testing.example .env.testing
          sed -i 's/STRIPE_PUBLIC_KEY=pk_test_/STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }}/g' .env.testing
          sed -i 's/STRIPE_SECRET_KEY=sk_test_/STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}/g' .env.testing
          sed -i 's/STRIPE_WEBHOOK_SECRET=whsec_/STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}/g' .env.testing

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, bcmath
          tools: composer:v2
          coverage: none
          ini-values: error_reporting=E_ALL

      - name: Set Laravel Version
        run: composer require "laravel/framework:^${{ matrix.laravel }}" --no-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: composer test
